### ISSUE TITLE
Motion Signal Representation during inference?

### ISSUE THREAD

**Issue by XuejiFang** [liyaowei-stu/ImageConductor#2]
Thank you for your excellent work!

However, I am curious about how the user-input motion signals are represented during inference. Are you using the motion data represented by estimated optical flow from your Camera-Only Motion Evaluation Dataset and Object-Only Motion Evaluation Dataset? If so, how can users interact with your model?

**Comment by liyaowei-stu** [comment]
The user-specified trajectories are represented as [n,t,2] tensor, and the [h,w,t,2] optical flow map can be obtained by calculating the difference between different trajectory points.
