### ISSUE TITLE
Data Curation

### ISSUE THREAD

**Issue by MingXiangL** [liyaowei-stu/ImageConductor#3]
Thank you for your outstanding work! Do you have any plans to release the dataset you've built and share the code used for data curation?

**Comment by liyaowei-stu** [comment]
Thank you for your kind words! We are currently in the process of organizing the code and dataset. We plan to release them as soon as possible. Stay tuned for updates!

**Comment by liyaowei-stu** [comment]
Stay tuned for updates!

**Comment by trouble-maker007** [comment]
@liyaowei-stu any update about the code of Trajectory-oriented video motion data construction workflow?
